/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedRoomsRoomIdRouteRouteImport } from './routes/_authenticated/rooms/$roomId/route'
import { Route as AuthenticatedRoomsRoomIdIndexRouteImport } from './routes/_authenticated/rooms/$roomId/index'
import { Route as ApiAuthSignupVerifyOtpRouteImport } from './routes/api/auth/signup/verify-otp'
import { Route as ApiAuthSignupRequestOtpRouteImport } from './routes/api/auth/signup/request-otp'
import { Route as AuthenticatedRoomsRoomIdBotsPlayerIdRouteImport } from './routes/_authenticated/rooms/$roomId/bots/$playerId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoomIdRouteRoute =
  AuthenticatedRoomsRoomIdRouteRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoomIdIndexRoute =
  AuthenticatedRoomsRoomIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoomsRoomIdRouteRoute,
  } as any)
const ApiAuthSignupVerifyOtpRoute = ApiAuthSignupVerifyOtpRouteImport.update({
  id: '/api/auth/signup/verify-otp',
  path: '/api/auth/signup/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRequestOtpRoute = ApiAuthSignupRequestOtpRouteImport.update({
  id: '/api/auth/signup/request-otp',
  path: '/api/auth/signup/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsRoomIdBotsPlayerIdRoute =
  AuthenticatedRoomsRoomIdBotsPlayerIdRouteImport.update({
    id: '/bots/$playerId',
    path: '/bots/$playerId',
    getParentRoute: () => AuthenticatedRoomsRoomIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteRouteWithChildren
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/auth/signup/request-otp': typeof ApiAuthSignupRequestOtpRoute
  '/api/auth/signup/verify-otp': typeof ApiAuthSignupVerifyOtpRoute
  '/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
  '/rooms/$roomId/bots/$playerId': typeof AuthenticatedRoomsRoomIdBotsPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/auth/signup/request-otp': typeof ApiAuthSignupRequestOtpRoute
  '/api/auth/signup/verify-otp': typeof ApiAuthSignupVerifyOtpRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdIndexRoute
  '/rooms/$roomId/bots/$playerId': typeof AuthenticatedRoomsRoomIdBotsPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteRouteWithChildren
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/auth/signup/request-otp': typeof ApiAuthSignupRequestOtpRoute
  '/api/auth/signup/verify-otp': typeof ApiAuthSignupVerifyOtpRoute
  '/_authenticated/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
  '/_authenticated/rooms/$roomId/bots/$playerId': typeof AuthenticatedRoomsRoomIdBotsPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/mcp'
    | '/rooms/$roomId'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/auth/signup/request-otp'
    | '/api/auth/signup/verify-otp'
    | '/rooms/$roomId/'
    | '/rooms/$roomId/bots/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/mcp'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/auth/signup/request-otp'
    | '/api/auth/signup/verify-otp'
    | '/rooms/$roomId'
    | '/rooms/$roomId/bots/$playerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/mcp'
    | '/_authenticated/'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/settings/notifications'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/auth/signup/request-otp'
    | '/api/auth/signup/verify-otp'
    | '/_authenticated/rooms/$roomId/'
    | '/_authenticated/rooms/$roomId/bots/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiAuthSignupRequestOtpRoute: typeof ApiAuthSignupRequestOtpRoute
  ApiAuthSignupVerifyOtpRoute: typeof ApiAuthSignupVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/$roomId/': {
      id: '/_authenticated/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRoomIdRouteRoute
    }
    '/api/auth/signup/verify-otp': {
      id: '/api/auth/signup/verify-otp'
      path: '/api/auth/signup/verify-otp'
      fullPath: '/api/auth/signup/verify-otp'
      preLoaderRoute: typeof ApiAuthSignupVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup/request-otp': {
      id: '/api/auth/signup/request-otp'
      path: '/api/auth/signup/request-otp'
      fullPath: '/api/auth/signup/request-otp'
      preLoaderRoute: typeof ApiAuthSignupRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$roomId/bots/$playerId': {
      id: '/_authenticated/rooms/$roomId/bots/$playerId'
      path: '/bots/$playerId'
      fullPath: '/rooms/$roomId/bots/$playerId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdBotsPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRoomsRoomIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRoomsRoomIdRouteRouteChildren {
  AuthenticatedRoomsRoomIdIndexRoute: typeof AuthenticatedRoomsRoomIdIndexRoute
  AuthenticatedRoomsRoomIdBotsPlayerIdRoute: typeof AuthenticatedRoomsRoomIdBotsPlayerIdRoute
}

const AuthenticatedRoomsRoomIdRouteRouteChildren: AuthenticatedRoomsRoomIdRouteRouteChildren =
  {
    AuthenticatedRoomsRoomIdIndexRoute: AuthenticatedRoomsRoomIdIndexRoute,
    AuthenticatedRoomsRoomIdBotsPlayerIdRoute:
      AuthenticatedRoomsRoomIdBotsPlayerIdRoute,
  }

const AuthenticatedRoomsRoomIdRouteRouteWithChildren =
  AuthenticatedRoomsRoomIdRouteRoute._addFileChildren(
    AuthenticatedRoomsRoomIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRoomsRoomIdRouteRoute: typeof AuthenticatedRoomsRoomIdRouteRouteWithChildren
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRoomsRoomIdRouteRoute:
    AuthenticatedRoomsRoomIdRouteRouteWithChildren,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiAuthSignupRequestOtpRoute: ApiAuthSignupRequestOtpRoute,
  ApiAuthSignupVerifyOtpRoute: ApiAuthSignupVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
